# Generated by Django 4.2.7 on 2023-12-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronic'), ('FN', 'Funiture'), ('VE', 'Vehicle'), ('TO', 'Tool'), ('', 'None')], default='', max_length=2),
        ),
    ]
