# Generated by Django 4.2.7 on 2023-12-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_item_bided_item_user_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_won',
        ),
    ]
