# Generated by Django 4.2.7 on 2023-12-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_item_user_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronic'), ('FN', 'Funiture'), ('VE', 'Vehicle'), ('TO', 'Tool'), ('FO', 'Food'), ('CL', 'Cloth'), ('EQ', 'Equipment'), ('', 'None')], default='', max_length=2),
        ),
    ]
