# Generated by Django 4.2.7 on 2023-12-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronic'), ('FN', 'Furniture'), ('VE', 'Vehicle'), ('TO', 'Tool'), ('FO', 'Food'), ('CL', 'Cloth'), ('EQ', 'Equipment'), ('', 'None')], default='', max_length=2),
        ),
    ]
